version: '3'
services:
  personal-website:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: personal-website
    container_name: personal-website
    restart: unless-stopped
    networks:
      - app-network
      - nginx-network

networks:
  app-network:
    driver: bridge
    name: personal-website
  nginx-network:
    driver: bridge
    name: nginx
